---
- hosts: all
  name: Add cis-91 packages
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - python3-pip 
          - python3-venv
    - name: Add groups
      ansible.builtin.group:
        