---
- hosts: all
  name: Add CIS-91 packages
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name: nodejs
        state: present
    - name: Create user 
      ansible.builtin.user:
        name: nodeuser
        system: yes
    - name: Clone repo
      ansible.builtin.git:
        repo: https://github.com/noe831/cis-91.git
        dest: /home/nodeuser/cis91
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /home/nodeuser/cis91
        owner: nodeuser
        group: nodeuser
    - name: Copy node_app.service file
      ansible.builtin.copy:
        src: /home/liliharbottle/cis-91/lab12/node_app.service
        dest: /lib/systemd/system/node_app.service
        owner: nodeuser
        group: nodeuser
        mode: 0644
    - name: Ensure service unit is running
      ansible.builtin.systemd:
        name: node_app.service
        daemon_reload: yes
        state: started
        enabled: yes